In [4]:
import numpy as np
import pandas as pd
import tensorflow
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from keras.layers import Dense

In [17]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [5]:
model=Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()#as keras initializes w and b from its own

[array([[-0.14637828, -0.94101155],
        [ 0.04034972, -0.118716  ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.7387179 ],
        [-0.07587039]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [12]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [14]:
import keras

In [15]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)

In [16]:
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [18]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100

4/4 [==============================] - 0s 5ms/step - loss: 27.9075
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 27.5691
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 27.2426
Epoch 4/100
4/4 [==============================] - 0s 5ms/step - loss: 26.9402
Epoch 5/100
4/4 [==============================] - 0s 3ms/step - loss: 26.5759
Epoch 6/100
4/4 [==============================] - 0s 5ms/step - loss: 26.2004
Epoch 7/100
4/4 [==============================] - 0s 1ms/step - loss: 25.8230
Epoch 8/100
4/4 [==============================] - 0s 2ms/step - loss: 25.4693
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 25.0622
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 24.6591
Epoch 11/100
4/4 [==============================] - 0s 0s/step - loss: 24.2505
Epoch 12/100
4/4 [==============================] - 0s 3ms/step - loss: 23.8483
Epoch 13/100
4/4 [==============================]

In [19]:
model.get_weights()

[array([[0.38449863, 0.38449863],
        [0.39109653, 0.39109653]], dtype=float32),
 array([0.29207435, 0.29207435], dtype=float32),
 array([[0.39357442],
        [0.39357442]], dtype=float32),
 array([0.21584797], dtype=float32)]