In [1]:
import numpy as np
import pandas as pd
import tensorflow
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from keras.layers import Dense

C:\Users\HP\AppData\Local\Temp\ipykernel_15236\621508485.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [3]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,12,0]], columns=['cgpa', 'profile_score', 'placed'])

In [4]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5             12       0

In [5]:
model=Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [7]:
model.get_weights()#as keras initializes w and b from its own

[array([[-0.01463282,  0.9301239 ],
        [ 1.1984872 ,  1.1730629 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.7796227 ],
        [0.66506517]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
import keras
optimizer=keras.optimizers.Adam(learning_rate=0.001)

In [12]:
model.compile(loss='binary_crossentropy',optimizer=optimizer)

In [13]:
model.fit(df.iloc[:,0:-1].values,df['placed'].values,epochs=100,verbose=1,batch_size=1)

Epoch 1/100

4/4 [==============================] - 0s 6ms/step - loss: 0.6974
Epoch 2/100
4/4 [==============================] - 0s 3ms/step - loss: 0.6970
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 0.6968
Epoch 4/100
4/4 [==============================] - 0s 3ms/step - loss: 0.6968
Epoch 5/100
4/4 [==============================] - 0s 0s/step - loss: 0.6967
Epoch 6/100
4/4 [==============================] - 0s 3ms/step - loss: 0.6967
Epoch 7/100
4/4 [==============================] - 0s 2ms/step - loss: 0.6966
Epoch 8/100
4/4 [==============================] - 0s 0s/step - loss: 0.6966
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 0.6966
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.6964
Epoch 11/100
4/4 [==============================] - 0s 0s/step - loss: 0.6966
Epoch 12/100
4/4 [==============================] - 0s 2ms/step - loss: 0.6963
Epoch 13/100
4/4 [==============================] - 0s 3ms/step